write RPAf design decision file
bptlab/ark_automate pull request #128
Opened 2021-02-16 18:44 UTC by kej-jay

fixes #88 

I wrote some documentation on why we decided to use the RPA framework

## Checklist before merge

**Developer's responsibilities**
* [X] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [X] updated the **documentation**

2021-02-17 08:58 UTC, SanJSp requested changes
content great! Typos should be fixed.

2021-02-17 08:58 UTC, SanJSp commented on wiki/Why-RPA-framework.md
> +* HTTP request functionality
* Browser

2021-02-17 08:58 UTC, SanJSp commented on wiki/Why-RPA-framework.md
> +* TagUI: This RPA software allows for easy bot creation using teh keywords 'type' and 'click'. This approach is really easy, but would require a graphically oriented interface to display the user whi
Typo: the

2021-02-17 08:58 UTC, SanJSp commented on wiki/Why-RPA-framework.md
> +* UI.Vision: Was initially created as a browser extension, but since has been extended to also allow automation on the desktop. We ecplicitly want to stress teh fact, that it was created with web aut
typo: the

2021-02-17 08:58 UTC, SanJSp commented on wiki/Why-RPA-framework.md
> +* UI.Vision: Was initially created as a browser extension, but since has been extended to also allow automation on the desktop. We ecplicitly want to stress teh fact, that it was created with web aut
typo: therefore

2021-02-17 08:58 UTC, SanJSp commented on wiki/Why-RPA-framework.md
> +* UI.Vision: Was initially created as a browser extension, but since has been extended to also allow automation on the desktop. We ecplicitly want to stress teh fact, that it was created with web aut
typo: explicitly

2021-03-06 16:13 UTC, lukashueller approved these changes
Nice, great documentation. It will take a little effort to write out the main points for the presentation, but apart from that I can't think of any other points that need to be included in the documentation.

2021-03-08 10:09 UTC, SanJSp approved these changes

2021-03-08 12:46 UTC, merged