Add basic modeling tool
bptlab/ark_automate pull request #29
Opened 2020-11-09 10:55 UTC by WolfgangDaniel

Fixes #3 

## Changes
A bpmn-js Modeler is implemented into the project now. All the necessary requirements have been documented in the readme file.

## Screenshots
Before: nothing
After:
![grafik](https://user-images.githubusercontent.com/42138601/98532617-3aa64480-2282-11eb-9641-f4d83a776a3f.png)

## Checklist before merge

**Developer's responsibilities**
* [ ] Approved by at least one developer: *enter reviewer here*
* [ ] **Pull request build** has passed
* [ ] Production backend has been updated to reflect new features and fix bugs
* [ ] tested locally (in all browsers if frontend)
* [ ] updated the docs
* [ ] added tests where necessary

**Product Owner's responsibilities**
* [ ] No issues have been found on staging environment
* [ ] Product Owner has approved the release

2020-11-09 12:53 UTC, lukashueller approved these changes
Looks very good. The README.md is very helpful!

2020-11-09 17:57 UTC, SanJSp requested changes

2020-11-09 17:57 UTC, SanJSp commented on client/src/pages/Modeler.js
> +import "bpmn-js-properties-panel/dist/assets/bpmn-js-properties-panel.css";
Single quotes

2020-11-09 17:57 UTC, SanJSp commented on client/src/pages/Modeler.js
> +      {/*<Title>Seite unseres Modelers</Title>*/}
has this worked uncommented?

2020-11-09 17:57 UTC, SanJSp commented on client/src/pages/Modeler.js
> +      {/*<BtnGotoHome/>*/}
see above

2020-11-11 06:39 UTC, WolfgangDaniel commented on client/src/pages/Modeler.js
> +      {/*<Title>Seite unseres Modelers</Title>*/}
yes

2020-11-11 06:41 UTC, WolfgangDaniel commented on client/src/pages/Modeler.js
> +      {/*<BtnGotoHome/>*/}
yes

2020-11-11 06:53 UTC, kej-jay approved these changes

2020-11-11 06:56 UTC, merged