Set-up Coding standards
bptlab/ark_automate pull request #295
Opened 2021-05-05 13:22 UTC by SanJSp

Fixes #94 

## Changes
In this PR a new site for our wiki regarding our coding standards is introduced. It covers our tools and some other standards we agreed on. **If you think there is something missing, please comment it!**

## Checklist before merge

**Developer's responsibilities**
* [ ] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [ ] **Pull request build** has passed
* [ ] **tested locally** (in at least chrome & firefox if frontend)
* [ ] updated the **documentation**
* [ ] added **tests** where necessary

2021-05-05 16:59 UTC, kej-jay reviewed
I'd like a hint to the wiki page where it says how the code should be documented. I thing that is very helpful when talking about inline comments to acknowledge other types of comments where we are actively wanting them

2021-05-05 16:59 UTC, kej-jay commented on wiki/Coding-Standards.md
> +- Do not fix Eslint warnings by adding the "fix-comment"
Vielleicht hier schreiben, dass wir es bestmöglich versuchen. Es ist im Ernstfall ja aber immer eine Option

2021-05-06 16:12 UTC, WolfgangDaniel requested changes
Looking good! Some small additions from my side.

2021-05-06 16:12 UTC, WolfgangDaniel commented on wiki/Coding-Standards.md
> +- We use arrow functions only in the frontend. Please do not use the `function` keyword.
We use arrow functions everywhere not just in the frontend

2021-05-06 16:12 UTC, WolfgangDaniel commented on wiki/Coding-Standards.md
> +- use `Application` in all cases instead of `App` (in context of supported RPA Applications)
Here I would add:
- use PascalCase for the naming of components (.jsx files)
- use camelCase for the naming of all other files (.js files mainly)
-  use UPPERCASE for constants

2021-05-09 13:20 UTC, lukashueller commented on wiki/Coding-Standards.md
> +Please do not use inline comments to explain the idea behind a variable or a function. Only use those for Sources where you found a special solution or woraround or for especially complex code snippe
Little typo "workaround"
```suggestion
Please do not use inline comments to explain the idea behind a variable or a function. Only use those for Sources where you found a special solution or workaround or for especially complex code snippets.
```

2021-05-09 13:22 UTC, lukashueller requested changes
I think that has become a very clear document. Thanks for transferring & extending the draft to the wiki! Please fix the one little thing as well as the comments of the others and then you can merge from my point of view!

2021-05-10 11:40 UTC, kej-jay approved these changes
Looks good to me now

2021-05-10 17:41 UTC, WolfgangDaniel approved these changes
Looking good now. Thanks!

2021-05-11 07:02 UTC, merged