Update Retro Action Points (Sprint 10)
bptlab/ark_automate pull request #309
Opened 2021-05-12 14:14 UTC by lukashueller

2021-05-12 14:49 UTC, WolfgangDaniel approved these changes

2021-05-16 20:00 UTC, SanJSp requested changes

2021-05-16 20:00 UTC, SanJSp commented on wiki/Team-Scrum-process.md
> -* We want to introduce a longer team coffee break on Wednesdays afternoons, every two weeks. The feelgood manager takes care of this.
Why was this deleted?

2021-05-17 08:33 UTC, SanJSp approved these changes

2021-05-17 08:33 UTC, SanJSp commented on wiki/Team-Scrum-process.md
> -* We want to introduce a longer team coffee break on Wednesdays afternoons, every two weeks. The feelgood manager takes care of this.
I just saw why it was deleted, it is stated above 
```
* Twice a week the team will have a common coffee break to talk about topics far away from work. This coffee break will take place on Mondays and Wednesdays from 16:00-16:30.
```

2021-05-24 16:46 UTC, kej-jay approved these changes

2021-05-24 17:35 UTC, merged