Rename variable to parameter or outputValue where applicable
bptlab/ark_automate pull request #311
Opened 2021-05-12 14:56 UTC by SanJSp

Fixes #222 
## Changes
This PR changes all occurrences of variable in the code with either parameter if it's an input or outputValue if it's an output. I will also update all ssots (ouputVariable to outputValue fields) in the database when this PR is approved 💁‍♂️ 

## Checklist before merge

**Developer's responsibilities**
* [x] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [x] **Pull request build** has passed
* [x] **tested locally** (in at least chrome & firefox if frontend)
* [x] updated the **documentation**
* [ ] added **tests** where necessary

2021-05-14 08:07 UTC, lukashueller commented on client/src/components/content/ModelerSidebar/ModelerSidebar.jsx
> +  outputValNameChangeHandler,
I see that the abbreviation has been used before, but I would still argue for using the long form of value :) 
```suggestion
  outputValueNameChangeHandler,
```

2021-05-14 08:08 UTC, lukashueller commented on client/src/components/content/ModelerSidebar/ModelerSidebar.jsx
> +              outputValNameChangeHandler(
same with the short form here
```suggestion
              outputValueNameChangeHandler(
```

2021-05-14 08:08 UTC, lukashueller commented on client/src/utils/modelerSidebarFunctionality/modelerSidebarFunctionality.js
> +const outputValNameChangeHandler = (activityId, newValue) => {
```suggestion
const outputValueNameChangeHandler = (activityId, newValue) => {
```

2021-05-14 08:09 UTC, lukashueller commented on client/src/utils/modelerSidebarFunctionality/modelerSidebarFunctionality.js
> +  outputValNameChangeHandler,
```suggestion
  outputValueNameChangeHandler,
```

2021-05-14 08:09 UTC, lukashueller commented on client/src/utils/modelerSidebarFunctionality/modelerSidebarFunctionality.test.js
> +    outputValNameChangeHandler(
```suggestion
    outputValueNameChangeHandler(
```

2021-05-14 08:39 UTC, lukashueller requested changes
Hi Sandro,
This looks like very focused, in-depth work to me. I've gone through all the files so far and I don't see any more wrong identifiers. I just hope now that everything continues to fit! ;) 

I would like you to write out all short forms of Value (`Val`) (see comments => you can assume directly, there are no more occurrences)

I would also like you to fix all typos of Parameter (someone always writes (`paramter`) there). 

Also the variable name `val` still exists in the RobotOverview. Can you please find a suitable identifier for it?

Thank you!

2021-05-17 08:29 UTC, WolfgangDaniel approved these changes
Thanks for a thorough job! Please implement Lukas requested changes before merging

2021-05-17 08:44 UTC, lukashueller approved these changes
looks good! Thanks for addressing my points!

2021-05-17 10:32 UTC, merged