Setup MIT license
bptlab/ark_automate pull request #328
Opened 2021-05-27 09:49 UTC by SanJSp

Fixes #271 

## Changes
This adds the MIT license to our repository.

## Checklist before merge

**Developer's responsibilities**
* [ ] **Assign** one or two developers
* [ ] **Change code** if reviewer(s) has/have requested it
* [ ] **Pull request build** has passed
* [ ] **tested locally** (in at least chrome & firefox if frontend)
* [ ] updated the **documentation**
* [ ] added **tests** where necessary

2021-05-27 10:11 UTC, WolfgangDaniel requested changes
Please also add a license part to the readme where you mention our open source license and provide a link to the license.md. And please add the license to docuGenerationHelper.js under the point "info". It should look like this: 
![grafik](https://user-images.githubusercontent.com/42138601/119808647-9e255600-bee4-11eb-85a9-b2b7e10f652d.png)

2021-05-28 14:00 UTC, lukashueller requested changes
Great work! But I miss, the associated pull request in the Local Client. We should also add our license there, right?

Furthermore: You still have to manually change the license in the GitHub Settings, right? Would you please take care of that as well?

2021-05-29 08:18 UTC, SanJSp commented
Pull request has been created. The Github Settings will be adapted automatically as soon as the license is merged into dev.

2021-05-29 11:46 UTC, kej-jay approved these changes

2021-05-29 15:27 UTC, WolfgangDaniel approved these changes

2021-05-29 15:42 UTC, lukashueller approved these changes

2021-05-30 09:49 UTC, merged