6 build simpler side pannel
bptlab/ark_automate pull request #47
Opened 2020-12-14 08:00 UTC by lukashueller

Fixes #6 

## Changes
**Implements a custom build sidepanel for our BPMN-Modeling-Interface.**
The following functionalities were added:
- select task / gateway or event and change their name in new sidebar
- select the activity and then select the app and the task to be automated using RPA
- all activities and applications are retrieved from MongoDB

## Screenshots
*Screenshot of our new interface with properties sidepanel and our new header navbar.*

![image](https://user-images.githubusercontent.com/36270527/102054735-1b06bc80-3dea-11eb-90f0-738c15830266.png)

## Checklist before merge

**Developer's responsibilities**
* [ ] Approved by at least one developer: *enter reviewer here* @SanJSp @WolfgangDaniel @kej-jay 
* [ ] **Pull request build** has passed
* [ ] Production backend has been updated to reflect new features and fix bugs
* [ ] tested locally (in all browsers if frontend)
* [ ] updated the docs
* [ ] added tests where necessary

**Product Owner's responsibilities**
* [ ] No issues have been found on staging environment
* [ ] Product Owner has approved the release

2020-12-14 11:43 UTC, SanJSp requested changes
After having changed the branch you want to merge into and merging dev into yours, the Pull Request got much smaller. Unfortunately, the selected values of RPATasks and Apps are currently not stored when switching to another activity. Because we have already merge Dev into this branch, this should work and I wish that you fix that (ether Erik or Lukas).

Apart from that I really like the look and I think you did a great job!

2020-12-14 11:43 UTC, SanJSp commented on client/src/components/BtnGotoModeler.jsx
> +export default gotoModeler;
newline at EOF

2020-12-14 11:43 UTC, SanJSp commented on client/src/components/headerNavbar/HeaderNavbar.jsx
> +}
newline at eof

2020-12-14 11:43 UTC, SanJSp commented on client/src/components/headerNavbar/HeaderNavbar.jsx
> +                {console.log(this.props.selectedKey)}
remove log

2020-12-14 11:43 UTC, SanJSp commented on client/src/components/properties-panel/propertiesPanelBuilder/PropertiesPanelBuilder.jsx
> +    // console.log('New Task selected: ' + value + ' for Application: ' + this.state['selectedApplication']);
should be removed

2020-12-14 11:43 UTC, SanJSp commented on client/src/components/properties-panel/propertiesPanelBuilder/PropertiesPanelBuilder.jsx
> +
remove empty line

2020-12-14 11:43 UTC, SanJSp commented on client/src/pages/Error.js
> +export default Error;
newline at eof

2020-12-14 11:43 UTC, SanJSp commented on client/src/pages/Home.js
> +export default Home;
newline at EOF

2020-12-14 11:43 UTC, SanJSp commented on client/src/pages/RobotFile.js
> +export default RobotFile;
newline at eof

2020-12-15 14:59 UTC, SanJSp approved these changes

2020-12-15 15:05 UTC, kej-jay approved these changes

2020-12-15 15:07 UTC, merged